#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RemoteForkAndroid.Resource", IsApplication=true)]

namespace RemoteForkAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::RemoteForkAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int bLoadPlaylist = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bNewVersion = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int bStartServer = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int bStopServer = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int etLogs = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int sIps = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int tvStatusServer = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int DevicesNotFound = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int ErrorStart = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ErrorStop = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LoadPlaylist = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int LoadedPlaylist = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int PlaylistBadFormat = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int StartServer = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int StartStatus = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int StartingStatus = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int StopServer = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int StopStatus = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int StopingStatus = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
